# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social', '0002_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupparticipation',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
