# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('my_social', '0004_groupevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCurrentPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='group/pic/'))),
                ('signing', models.CharField(default='', max_length=256)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_social.Group')),
            ],
        ),
        migrations.AddField(
            model_name='groupcurrentpic',
            name='currentpic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_social.GroupPic'),
        ),
        migrations.AddField(
            model_name='groupcurrentpic',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentpic', to='my_social.Group'),
        ),
    ]
