# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_social', '0006_auto_20160324_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 24, 10, 50, 59, 545374, tzinfo=utc), verbose_name='date started'),
            preserve_default=False,
        ),
    ]
