# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_social', '0007_auto_20160324_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sended_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
