# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_social', '0008_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 25, 20, 27, 10, 269146, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
