# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social', '0010_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='read',
        ),
    ]
