# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='currentpic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserPic'),
        ),
    ]
