# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160307_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='unread_messages',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='unread_notifications',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
