# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='timezone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
