# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20160325_1033'),
        ('accounts', '0008_auto_20160326_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageToEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='base.Event')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.Language')),
            ],
        ),
    ]
