# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_languagetoevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSearchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Language')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSearchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.BooleanField(default=False)),
                ('time', models.BooleanField(default=False)),
                ('language', models.BooleanField(default=False)),
                ('beginning', models.DateTimeField(verbose_name='beginning')),
                ('ending', models.DateTimeField(verbose_name='ending')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
