# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_languagesearchsettings_usersearchsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchsettings',
            name='beginning',
            field=models.DateTimeField(null=True, verbose_name='beginning'),
        ),
        migrations.AlterField(
            model_name='usersearchsettings',
            name='ending',
            field=models.DateTimeField(null=True, verbose_name='ending'),
        ),
    ]
