# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_languagetouser_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagesearchsettings',
            name='language',
        ),
        migrations.RemoveField(
            model_name='languagesearchsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='LanguageSearchSettings',
        ),
    ]
