# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-31 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userinfo_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='residence',
        ),
    ]
