# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_userinfo_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchsettings',
            name='location',
            field=models.CharField(default='WORLD', max_length=32),
        ),
    ]
