# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userplatform_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplatform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL),
        ),
    ]
