# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20160401_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchsettings',
            name='platform',
            field=models.BooleanField(default=False),
        ),
    ]
