# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-03 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_usersearchsettings_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_active',
            field=models.DateTimeField(null=True, verbose_name='last active'),
        ),
    ]
