# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userinfo_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
