# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_userinfo_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagetoevent',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='languages_plus.Language'),
        ),
        migrations.AlterField(
            model_name='languagetouser',
            name='language',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
