# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_userinfo_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagetoevent',
            name='language',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='languagetouser',
            name='language',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
