# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gid',
        ),
        migrations.AddField(
            model_name='event',
            name='before',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 16, 19, 18, 3, 681105, tzinfo=utc), verbose_name='active before'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 16, 19, 18, 17, 655034, tzinfo=utc), verbose_name='date started'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
