# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160216_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.FileField(default='media/games/covers/not_available.gif', upload_to=''),
        ),
    ]
