# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160218_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
