# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20160220_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant_number',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
