# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_event_participant_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
