# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 13:40
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20160305_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='games/covers/')),
        ),
    ]
