# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 07:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20160324_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 25, 7, 35, 56, 581561, tzinfo=utc), verbose_name='start time'),
            preserve_default=False,
        ),
    ]
