# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_event_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
