# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-31 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Platform'),
        ),
    ]
