# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_event_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_shortcut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='shortcut',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
