# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20160406_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-event_number']},
        ),
        migrations.AddField(
            model_name='game',
            name='event_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
