# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_event_participant_number'),
        ('social', '0002_auto_20160227_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
        migrations.AddField(
            model_name='application',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.Notification'),
        ),
    ]
