# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20160228_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 28, 12, 10, 22, 462265, tzinfo=utc), verbose_name='date started'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 28, 12, 10, 42, 51174, tzinfo=utc), verbose_name='date started'),
            preserve_default=False,
        ),
    ]
